version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Map container's port 8080 to host's port 8080
    depends_on:
      - mongodb
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongodb:27017/test
      SERVER_SERVLET_CONTEXT_PATH: /api

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017" # Map container's port 27017 to host's port 27017
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
